[package]
name = "deposition"
version = "0.1.0"
authors = ["ede1998 <online@erik-hennig.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32-hal", version = "0.12.0" }
esp-backtrace = { version = "0.7.0", features = [
    "esp32",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { version = "0.5.0", features = ["esp32"] }
ssd1306 = "0.7.1"
embedded-graphics = "0.7.1"
