[package]
name = "deposition"
version = "0.1.0"
authors = ["ede1998 <online@erik-hennig.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32-hal", version = "0.12.0", features = ["embassy-time-timg0", "embassy"] }
esp-backtrace = { version = "0.7.0", features = [
    "esp32",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { version = "0.5.0", features = ["esp32"] }
ssd1306 = "0.7.1"
embedded-graphics = "0.8.0"
embassy-executor = { version = "0.2.0", features = ["arch-xtensa", "executor-thread", "integrated-timers", "nightly"] }
static_cell = "1.0.0"
embassy-sync = { version = "0.2.0", features = ["nightly"] }
embassy-time = { version = "0.1.1", features = ["nightly"] }
